export const PRICING_PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: "₹12,999",
    billingNote: "/month · billed monthly",
    leadLimit: "Up to 1,000 leads/mo",
    isPopular: false,
    description: "Essential lead routing and pipeline automation for growing sales teams.",
    features: [
      "Unlimited team seats",
      "Up to 1,000 incoming leads/mo",
      "WhatsApp Business & Meta Ads sync",
      "Round-robin lead distribution",
      "Standard SLA alerts & reminders",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: "₹17,999",
    billingNote: "/month · billed monthly",
    leadLimit: "Up to 5,000 leads/mo",
    isPopular: true,
    description: "Advanced automation, weighted rules, and multichannel pipelines.",
    features: [
      "Unlimited team seats",
      "Up to 5,000 incoming leads/mo",
      "Weighted distribution & cap rules",
      "Multiple custom pipelines",
      "Full audit trail & export",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "₹19,999",
    billingNote: "/month · billed monthly",
    leadLimit: "Unlimited leads/mo",
    isPopular: false,
    description: "Maximum scale with dedicated priority support and custom integrations.",
    features: [
      "Unlimited team seats",
      "Unlimited incoming leads/mo",
      "Custom ERP & property portal webhooks",
      "Custom SLA policies & escalations",
      "Dedicated account manager",
    ],
  },
];
